[package]
name = "exirs-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
libc = "0.2.150"

[build-dependencies]
bindgen = "0.69.1"
