[package]
name = "exirs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
bitflags = "2.5.0"
ffi = { package = "exirs-sys", path = "../exirs-sys" }
thiserror = "1.0.60"
